services:
  db:
    image: mysql:8.0
    container_name: proyectos2-db
    environment:
      MYSQL_DATABASE: UrbanHelp
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
    ports:
      - "3307:3306"
    volumes:
      - postgres-data:/var/lib/mysql
      - ./bbdd.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u postgres -ppostgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyectos2-backend
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: postgres
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: UrbanHelp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: proyectos2-frontend
    depends_on:
      - backend
    ports:
      - "8081:8081"

volumes:
  postgres-data: