global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Tema 7: métricas de MySQL via mysqld_exporter
  - job_name: "mysql"
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
